/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── shadcn/ui CSS variable tokens ──────────────────────────────────
        background:        "hsl(var(--background))",
        foreground:        "hsl(var(--foreground))",
        card:              "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover:           "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border:     "hsl(var(--border))",
        input:      "hsl(var(--input))",
        ring:       "hsl(var(--ring))",

        // ── SmartSQL surface layers ──────────────────────────────────────
        "surface-1":  "hsl(var(--surface-1))",
        "surface-2":  "hsl(var(--surface-2))",
        "surface-3":  "hsl(var(--surface-3))",

        // ── Status colors ────────────────────────────────────────────────
        error:        "hsl(var(--destructive))",
        warning:      "hsl(var(--warning))",
        success:      "hsl(var(--success))",

        // ── Legacy brand tokens (preserved for backward compatibility) ───
        brand: {
          50:  "#0F172A",
          100: "#1E293B",
          500: "#3b82f6",
          600: "#3b82f6",
          700: "#2563eb",
          900: "#1e3a8a",
        },
        "on-primary":                     "#ffffff",
        "code-output":                    "#4ade80",
        "code-function":                  "#facc15",
        "code-literal":                   "#fb923c",
        "code-keyword":                   "#60a5fa",
        "role-admin":                     "#EF4444",
        "role-analyst":                   "#3B82F6",
        "surface":                        "#0F172A",
        "on-surface":                     "#F8FAFC",
        "on-background":                  "#F8FAFC",
        "on-surface-variant":             "#CBD5E1",
        "surface-bright":                 "#111827",
        "surface-dim":                    "#09090B",
        "tertiary":                       "#8B5CF6",
        "tertiary-ai":                    "#8B5CF6",
        "secondary-container":            "#1E293B",
        "primary-container":              "#3B82F6",
        "error-container":                "#7F1D1D",
        "code-surface":                   "#0F172A",
        "inverse-surface":                "#F8FAFC",
        "inverse-primary":                "#60A5FA",
        "outline":                        "#27272A",
        "outline-variant":                "#1E293B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
      spacing: {
        "section-gap":         "24px",
        "nav-item-padding":    "12px",
        "card-p":              "20px",
        "card-padding":        "20px",
        "card-padding-lg":     "24px",
        "page-p":              "32px",
        "page-padding":        "32px",
        "sidebar-width":       "240px",
        "sidebar-w":           "240px",
        "container-max-sm":    "640px",
        "container-max-md":    "768px",
        "container-max-lg":    "1024px",
        "container-max-xl":    "1280px",
        xs:    "4px",
        sm:    "12px",
        md:    "16px",
        lg:    "24px",
        xl:    "32px",
        "2xl": "40px",
        "3xl": "64px",
        base:  "8px",
      },
      fontFamily: {
        mono:         ["JetBrains Mono", "Fira Code", "monospace"],
        display:      ["Inter", "sans-serif"],
        "headline-lg":["Inter", "sans-serif"],
        "headline-md":["Inter", "sans-serif"],
        "headline-sm":["Inter", "sans-serif"],
        "title-lg":   ["Inter", "sans-serif"],
        "title-md":   ["Inter", "sans-serif"],
        "title-sm":   ["Inter", "sans-serif"],
        "body-lg":    ["Inter", "sans-serif"],
        "body-md":    ["Inter", "sans-serif"],
        "label-lg":   ["Inter", "sans-serif"],
        "label-md":   ["Inter", "sans-serif"],
        "label-sm":   ["Inter", "sans-serif"],
        "code-md":    ["JetBrains Mono", "monospace"],
        "code-sm":    ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        display:      ["60px",  { lineHeight: "66px",  letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg":["36px",  { lineHeight: "44px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":["28px",  { lineHeight: "36px",  letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm":["22px",  { lineHeight: "28px",  fontWeight: "700" }],
        "title-lg":   ["18px",  { lineHeight: "28px",  fontWeight: "600" }],
        "title-md":   ["16px",  { lineHeight: "24px",  fontWeight: "600" }],
        "title-sm":   ["14px",  { lineHeight: "20px",  fontWeight: "600" }],
        "body-lg":    ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":    ["14px",  { lineHeight: "22px",  fontWeight: "400" }],
        "label-lg":   ["14px",  { lineHeight: "20px",  fontWeight: "600" }],
        "label-md":   ["12px",  { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm":   ["11px",  { lineHeight: "16px",  letterSpacing: "0.04em", fontWeight: "500" }],
        "code-md":    ["13px",  { lineHeight: "22px",  fontWeight: "400" }],
        "code-sm":    ["11px",  { lineHeight: "18px",  fontWeight: "400" }],
      },
      animation: {
        "fade-in-up": "fade-in-up 0.35s ease-out forwards",
        "scale-in":   "scale-in 0.25s ease-out forwards",
        "slide-up":   "slide-up 0.4s ease-out forwards",
        "pulse-dot":  "pulse-dot 1.5s ease-in-out infinite",
      },
      keyframes: {
        "fade-in-up": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in":   { "0%": { opacity: "0", transform: "scale(0.96)" },      "100%": { opacity: "1", transform: "scale(1)" } },
        "slide-up":   { "0%": { opacity: "0", transform: "translateY(16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "pulse-dot":  { "0%,100%": { opacity: "0.3" }, "50%": { opacity: "1" } },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
