/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Legacy brand tokens (used by app shell components) ────────────────
        brand: {
          50:  "#eff6ff",
          100: "#dbeafe",
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
          900: "#1e3a8a",
        },
        // ── Stitch MD3 tokens (used by landing page & design system) ─────────
        "surface-container-low":          "#f3f3fe",
        "on-secondary-fixed-variant":     "#404758",
        "code-output":                    "#4ade80",
        "surface-tint":                   "#0053db",
        "on-primary":                     "#ffffff",
        "code-function":                  "#facc15",
        "on-secondary":                   "#ffffff",
        "on-error-container":             "#93000a",
        "background":                     "#f9fafb",
        "on-secondary-container":         "#5c6274",
        "surface-container-high":         "#e7e7f3",
        "on-tertiary-container":          "#f7edff",
        "tertiary-fixed":                 "#eaddff",
        "code-literal":                   "#fb923c",
        "on-tertiary-fixed-variant":      "#5a00c6",
        "error":                          "#ef4444",
        "surface-container":              "#f3f4f6",
        "on-error":                       "#ffffff",
        "tertiary":                       "#6a1edb",
        "on-primary-container":           "#eeefff",
        "on-primary-fixed":               "#00174b",
        "secondary-container":            "#d9dff5",
        "surface-container-highest":      "#e1e2ed",
        "error-container":                "#ffdad6",
        "secondary":                      "#575e70",
        "inverse-on-surface":             "#f0f0fb",
        "role-admin":                     "#b91c1c",
        "on-background":                  "#191b23",
        "on-tertiary-fixed":              "#25005a",
        "primary-fixed":                  "#dbe1ff",
        "primary-container":              "#2563eb",
        "surface":                        "#ffffff",
        "role-analyst":                   "#1d4ed8",
        "code-surface":                   "#111827",
        "on-surface-variant":             "#434655",
        "secondary-fixed-dim":            "#c0c6db",
        "code-keyword":                   "#60a5fa",
        "warning":                        "#eab308",
        "on-primary-fixed-variant":       "#003ea8",
        "tertiary-fixed-dim":             "#d2bbff",
        "tertiary-ai":                    "#7c3aed",
        "tertiary-container":             "#8343f4",
        "on-tertiary":                    "#ffffff",
        "outline-variant":                "#c3c6d7",
        "primary":                        "#004ac6",
        "surface-variant":                "#e1e2ed",
        "inverse-primary":                "#b4c5ff",
        "inverse-surface":                "#2e3039",
        "on-secondary-fixed":             "#141b2b",
        "surface-dim":                    "#d9d9e5",
        "success":                        "#22c55e",
        "surface-container-lowest":       "#ffffff",
        "secondary-fixed":                "#dce2f7",
        "on-surface":                     "#191b23",
        "surface-bright":                 "#faf8ff",
        "outline":                        "#e5e7eb",
        "primary-fixed-dim":              "#b4c5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
      spacing: {
        "section-gap":         "24px",
        "nav-item-padding":    "12px",
        "card-p":              "20px",
        "card-padding":        "20px",
        "card-padding-lg":     "24px",
        "page-p":              "32px",
        "page-padding":        "32px",
        "sidebar-width":       "240px",
        "sidebar-w":           "240px",
        "container-max-sm":    "640px",
        "container-max-md":    "768px",
        "container-max-lg":    "1024px",
        "container-max-xl":    "1280px",
        xs:    "4px",
        sm:    "12px",
        md:    "16px",
        lg:    "24px",
        xl:    "32px",
        "2xl": "40px",
        "3xl": "64px",
        base:  "8px",
      },
      fontFamily: {
        mono:         ["JetBrains Mono", "Fira Code", "monospace"],
        display:      ["Inter", "sans-serif"],
        "headline-lg":["Inter", "sans-serif"],
        "headline-md":["Inter", "sans-serif"],
        "headline-sm":["Inter", "sans-serif"],
        "title-lg":   ["Inter", "sans-serif"],
        "title-md":   ["Inter", "sans-serif"],
        "title-sm":   ["Inter", "sans-serif"],
        "body-lg":    ["Inter", "sans-serif"],
        "body-md":    ["Inter", "sans-serif"],
        "label-lg":   ["Inter", "sans-serif"],
        "label-md":   ["Inter", "sans-serif"],
        "label-sm":   ["Inter", "sans-serif"],
        "code-md":    ["JetBrains Mono", "monospace"],
        "code-sm":    ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        display:      ["60px",  { lineHeight: "66px",  letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg":["36px",  { lineHeight: "44px",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md":["28px",  { lineHeight: "36px",  letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm":["22px",  { lineHeight: "28px",  fontWeight: "700" }],
        "title-lg":   ["18px",  { lineHeight: "28px",  fontWeight: "600" }],
        "title-md":   ["16px",  { lineHeight: "24px",  fontWeight: "600" }],
        "title-sm":   ["14px",  { lineHeight: "20px",  fontWeight: "600" }],
        "body-lg":    ["18px",  { lineHeight: "28px",  fontWeight: "400" }],
        "body-md":    ["14px",  { lineHeight: "22px",  fontWeight: "400" }],
        "label-lg":   ["14px",  { lineHeight: "20px",  fontWeight: "600" }],
        "label-md":   ["12px",  { lineHeight: "16px",  letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm":   ["11px",  { lineHeight: "16px",  letterSpacing: "0.04em", fontWeight: "500" }],
        "code-md":    ["13px",  { lineHeight: "22px",  fontWeight: "400" }],
        "code-sm":    ["11px",  { lineHeight: "18px",  fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
