/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background:        "hsl(var(--background))",
        foreground:        "hsl(var(--foreground))",
        card:              "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover:           "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border:     "hsl(var(--border))",
        input:      "hsl(var(--input))",
        ring:       "hsl(var(--ring))",
        "surface-1":  "hsl(var(--surface-1))",
        "surface-2":  "hsl(var(--surface-2))",
        "surface-3":  "hsl(var(--surface-3))",
        error:        "hsl(var(--destructive))",
        warning:      "hsl(var(--warning))",
        success:      "hsl(var(--success))",
      },
      borderRadius: {
        xs:      "4px",
        sm:      "6px",
        DEFAULT: "8px",
        md:      "8px",
        lg:      "12px",
        xl:      "16px",
        "2xl":   "24px",
        full:    "9999px",
      },
      spacing: {
        "section-gap":       "32px",
        "nav-item-padding":  "12px",
        "card-p":            "24px",
        "card-padding":      "24px",
        "card-padding-lg":   "32px",
        "page-p":            "32px",
        "page-padding":      "32px",
        "sidebar-width":     "240px",
        "sidebar-w":         "240px",
        xxs:   "4px",
        xs:    "8px",
        sm:    "12px",
        md:    "16px",
        lg:    "20px",
        xl:    "24px",
        xxl:   "32px",
        xxxl:  "40px",
        "section-sm": "48px",
        section: "64px",
        "section-lg": "96px",
        hero: "120px",
      },
      fontFamily: {
        sans:  ["Inter", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono:  ["Geist Mono", "SF Mono", "Menlo", "Consolas", "monospace"],
      },
      fontSize: {
        display:      ["48px", { lineHeight: "1.10", letterSpacing: "-1px", fontWeight: "600" }],
        "headline-lg":["36px", { lineHeight: "1.20", letterSpacing: "-0.5px", fontWeight: "600" }],
        "headline-md":["28px", { lineHeight: "1.25", fontWeight: "600" }],
        "headline-sm":["18px", { lineHeight: "1.40", fontWeight: "600" }],
        "body-lg":    ["16px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-md":    ["14px", { lineHeight: "1.50", fontWeight: "400" }],
        "body-sm":    ["13px", { lineHeight: "1.40", fontWeight: "400" }],
        "label-lg":   ["14px", { lineHeight: "1.30", fontWeight: "500" }],
        "label-md":   ["13px", { lineHeight: "1.40", fontWeight: "600" }],
        "label-sm":   ["11px", { lineHeight: "1.40", letterSpacing: "0.5px", fontWeight: "600" }],
        "code-md":    ["14px", { lineHeight: "1.50", fontWeight: "400" }],
        "code-sm":    ["13px", { lineHeight: "1.40", fontWeight: "400" }],
      },
      animation: {
        "fade-in-up":      "fade-in-up 0.4s ease-out forwards",
        "fade-in":         "fade-in 0.3s ease-out forwards",
        "scale-in":        "scale-in 0.25s ease-out forwards",
        "slide-up":        "slide-up 0.45s ease-out forwards",
        "slide-in-right":  "slide-in-right 0.3s ease-out forwards",
        "pulse-dot":       "pulse-dot 1.5s ease-in-out infinite",
        "shimmer":         "shimmer 1.5s infinite",
      },
      keyframes: {
        "fade-in-up": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in":    { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "scale-in":   { "0%": { opacity: "0", transform: "scale(0.96)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        "slide-up":   { "0%": { opacity: "0", transform: "translateY(16px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "slide-in-right": { "0%": { opacity: "0", transform: "translateX(8px)" }, "100%": { opacity: "1", transform: "translateX(0)" } },
        "pulse-dot":  { "0%,100%": { opacity: "0.3" }, "50%": { opacity: "1" } },
        "shimmer":    { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
